AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI application with Mangum handler

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.13

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  JwtSecret:
    Type: String
    Default: 'jwt-secret'
    Description: JWT secret
  
  JwtAlgorithm:
    Type: String
    Default: 'HS256'
    Description: JWT algorithm

Resources:
  # Dead Letter Queue for failed orders
  PoshubOrdersDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "poshub-orders-dlq"

  # Main Orders Queue with DLQ configuration
  PoshubOrdersQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "poshub-orders-dev"
      VisibilityTimeout: 30 
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PoshubOrdersDlq.Arn
        maxReceiveCount: 3

  # SSM Parameter to store the queue URL
  QueueUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: QUEUE_URL
      Type: String
      Value: !Ref PoshubOrdersQueue
      Description: URL of the main orders queue

  # Layer depuis votre fichier ZIP
  PythonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${Environment}-python-deps"
      Description: Python dependencies including FastAPI and Mangum
      ContentUri: layers/python-deps-layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Retain

  # Fonction FastAPI
  FastApiFunctionIac:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.handler
      Runtime: python3.13
      Layers:
        - !Ref PythonDependenciesLayer
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: INFO
          JWT_SECRET: !Ref JwtSecret
          JWT_ALGORITHM: !Ref JwtAlgorithm
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
        - Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt PoshubOrdersQueue.Arn
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: '*'

      Events:
        # Capturer toutes les routes
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref FastApiGateway
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref FastApiGateway

  OrderProcessorFunctionIac:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: order_processor.lambda_handler
      Runtime: python3.13
      Layers:
        - !Ref PythonDependenciesLayer
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: INFO
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt PoshubOrdersQueue.QueueName
        - Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
      Events:
        OrdersQueue:
          Type: SQS
          Properties:
            BatchSize: 10
            Enabled: true
            Queue: !GetAtt PoshubOrdersQueue.Arn
            FunctionResponseTypes:
              - ReportBatchItemFailures

  # API Gateway
  FastApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

Outputs:
  FastApiUrl:
    Description: "FastAPI URL"
    Value: !Sub "https://${FastApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
    Export:
      Name: !Sub "${AWS::StackName}-FastApiUrl"
  
  FunctionArn:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastApiFunctionIac.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"

  OrdersQueueUrl:
    Description: "Orders Queue URL"
    Value: !Ref PoshubOrdersQueue
    Export:
      Name: !Sub "${AWS::StackName}-OrdersQueueUrl"

  OrdersDlqUrl:
    Description: "Orders Dead Letter Queue URL"
    Value: !Ref PoshubOrdersDlq
    Export:
      Name: !Sub "${AWS::StackName}-OrdersDlqUrl"